import assert from 'node:assert/strict';
const pointCount = (s: string): number => [...s].length;
assert.equal(pointCount('A😀B'), 3);
assert.equal('A😀B'.length, 4);
const tags = new Set(['a:1', 'b:1']);
tags.delete('a:1');
assert.deepEqual([...tags], ['b:1']);
const pending = [3, 2, 1];
let clock = 0;
while (pending.includes(clock + 1)) pending.splice(pending.indexOf(++clock), 1);
assert.equal(clock, 3);
const siblings = [{actor:'a',seq:1,time:1},{actor:'b',seq:1,time:1},{actor:'a',seq:2,time:2}];
siblings.sort((a,b) => b.time-a.time || (a.actor < b.actor ? 1 : a.actor > b.actor ? -1 : 0) || b.seq-a.seq);
assert.deepEqual(siblings.map(x => `${x.actor}:${x.seq}`), ['a:2','b:1','a:1']);
console.log('spike: native TypeScript, Unicode, OR-tags, causal fixed point, ASCII ordering PASS');
