import { TieredEngine } from '../src/tiering.js';
import { Heap } from '../src/collection.js';
import { ShapeRegistry } from '../src/caches.js';
const heap = new Heap(8), engine = new TieredEngine({ heap, baselineThreshold: 2, optimizeThreshold: 4, physicalRegisters: 1 });
engine.define('sum', { registers: 3, arity: 2, code: [['ADD', 2, 0, 1], ['RETURN', 2]] });
for (let i = 0; i < 5; i++) console.log('sum', engine.call('sum', [20, 22]), engine.info('sum').state);
console.log('type deopt', engine.call('sum', ['4', 2]), engine.info('sum'));
const object = new ShapeRegistry().create({ x: 7 });
engine.define('get', { registers: 2, arity: 1, code: [['GET', 1, 0, 'x'], ['RETURN', 1]] });
for (let i = 0; i < 4; i++) engine.call('get', [object]);
object.set('y', 8);
console.log('shape deopt', engine.call('get', [object]), engine.info('get'));
heap.allocate({ garbage: true });
const leaf = heap.allocate({ x: 42 }), root = heap.allocate({ child: leaf });
console.log('GC', heap.collect([root]), 'stable value', heap.get(heap.get(root, 'child'), 'x'));
