<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Pricing.Discounts\Pricing.Discounts.csproj" />
    <ProjectReference Include="..\Pricing.Tax\Pricing.Tax.csproj" />
    <ProjectReference Include="..\Pricing.Orders\Pricing.Orders.csproj" />
    <ProjectReference Include="..\Pricing.Money\Pricing.Money.csproj" />
    <ProjectReference Include="..\Pricing.Coupons\Pricing.Coupons.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
